Testing
YunoHost-Apps/moodle_ynh pull request #32
Opened 2021-02-14 21:38 UTC by ericgaspar

- *Upgrade to veersion 3.10.1*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/moodle_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/moodle_ynh%20PR-NUM-%20(USERNAME)/)

2021-02-14 21:43 UTC, ericgaspar commented
!testme

2021-02-16 12:57 UTC, yalh76 requested changes

2021-02-16 12:57 UTC, yalh76 commented on scripts/install
> +	ynh_permission_update --permission="main" --add="visitors"
you should remove L53 `ynh_app_setting_set --app="$app" --key=is_public --value="$is_public"`

2021-02-23 03:38 UTC, yalh76 approved these changes

2021-02-25 14:10 UTC, merged