Set rights
YunoHost-Apps/moodle_ynh pull request #45
Opened 2021-06-04 09:35 UTC by ericgaspar

## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

2021-06-04 09:35 UTC, ericgaspar commented
!testme

2021-06-15 22:17 UTC, yalh76 commented
!testme

2021-06-16 10:41 UTC, yalh76 requested changes

2021-06-16 10:41 UTC, yalh76 commented on scripts/upgrade
> +	ynh_secure_remove --dest_dir="$final_path"
```suggestion
	ynh_secure_remove --file="$final_path"
```

2021-06-16 11:55 UTC, ericgaspar commented
!testme

2021-06-16 19:28 UTC, yalh76 requested changes

2021-06-16 19:28 UTC, yalh76 commented on scripts/upgrade
> +	ynh_secure_remove --file="$final_path"
you should backup and restore `/var/www/moodle/admin/cli/../../config.php` during source upgrade ^^

2021-06-17 06:26 UTC, merged